------------- CREATE SCHEMA

CREATE SCHEMA
`golang` DEFAULT CHARACTER
SET utf8
COLLATE utf8_bin ;



--------TELEFONE

CREATE TABLE `telefone` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TIPO` int(10) DEFAULT NULL,
  `DD` int(2) DEFAULT NULL,
  `NUMERO` int(15) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


----- IDENTIFICADOR


CREATE TABLE `identificador` (
  `CPF` bigint NOT NULL,
  `RG` bigint DEFAULT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE KEY `CPF_UNIQUE` (`CPF`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


-------ENDERECO
CREATE TABLE `endereco` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CEP` int(11) DEFAULT NULL,
  `LOGRADOURO` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `COMPLEMENTO` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `BAIRRO` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `CIDADE` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `UF` varchar(2) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


--- PESSOS
CREATE TABLE `pessoa` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `DATA_NASCIMENTO` timestamp NULL DEFAULT NULL,
  `EMAIL` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `TELEFONE_ID` bigint(20) DEFAULT NULL,
  `ENDERECO_ID` int(11) DEFAULT NULL,
  `REMIDER` timestamp NULL DEFAULT NULL,
  `IEDNTIFICADOR_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `ENDERECO_FK_idx` (`ENDERECO_ID`),
  KEY `TELEFONE_FK_idx` (`TELEFONE_ID`),
  KEY `IDENTIFICADOR_FK_idx` (`IEDNTIFICADOR_ID`),
  CONSTRAINT `ENDERECO_FK` FOREIGN KEY (`ENDERECO_ID`) REFERENCES `endereco` (`ID`),
  CONSTRAINT `IDENTIFICADOR_FK` FOREIGN KEY (`IEDNTIFICADOR_ID`) REFERENCES `identificador` (`CPF`),
  CONSTRAINT `TELEFONE_FK` FOREIGN KEY (`TELEFONE_ID`) REFERENCES `telefone` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
