// Code generated by protoc-gen-go. DO NOT EDIT.
// source: endereco-service.proto

package pessoa

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Objeto Endereço
type Endereco struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cep                  int64    `protobuf:"varint,2,opt,name=cep,proto3" json:"cep,omitempty"`
	Logradouro           string   `protobuf:"bytes,3,opt,name=logradouro,proto3" json:"logradouro,omitempty"`
	Complemento          string   `protobuf:"bytes,4,opt,name=complemento,proto3" json:"complemento,omitempty"`
	Bairro               string   `protobuf:"bytes,5,opt,name=bairro,proto3" json:"bairro,omitempty"`
	Cidade               string   `protobuf:"bytes,6,opt,name=cidade,proto3" json:"cidade,omitempty"`
	Uf                   string   `protobuf:"bytes,7,opt,name=uf,proto3" json:"uf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endereco) Reset()         { *m = Endereco{} }
func (m *Endereco) String() string { return proto.CompactTextString(m) }
func (*Endereco) ProtoMessage()    {}
func (*Endereco) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4e4356cce7d54fb, []int{0}
}

func (m *Endereco) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endereco.Unmarshal(m, b)
}
func (m *Endereco) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endereco.Marshal(b, m, deterministic)
}
func (m *Endereco) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endereco.Merge(m, src)
}
func (m *Endereco) XXX_Size() int {
	return xxx_messageInfo_Endereco.Size(m)
}
func (m *Endereco) XXX_DiscardUnknown() {
	xxx_messageInfo_Endereco.DiscardUnknown(m)
}

var xxx_messageInfo_Endereco proto.InternalMessageInfo

func (m *Endereco) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Endereco) GetCep() int64 {
	if m != nil {
		return m.Cep
	}
	return 0
}

func (m *Endereco) GetLogradouro() string {
	if m != nil {
		return m.Logradouro
	}
	return ""
}

func (m *Endereco) GetComplemento() string {
	if m != nil {
		return m.Complemento
	}
	return ""
}

func (m *Endereco) GetBairro() string {
	if m != nil {
		return m.Bairro
	}
	return ""
}

func (m *Endereco) GetCidade() string {
	if m != nil {
		return m.Cidade
	}
	return ""
}

func (m *Endereco) GetUf() string {
	if m != nil {
		return m.Uf
	}
	return ""
}

// Requisito para criar uma nova pessoa
type CriarEnderecoRequest struct {
	Api                  string    `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Endereco             *Endereco `protobuf:"bytes,2,opt,name=endereco,proto3" json:"endereco,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CriarEnderecoRequest) Reset()         { *m = CriarEnderecoRequest{} }
func (m *CriarEnderecoRequest) String() string { return proto.CompactTextString(m) }
func (*CriarEnderecoRequest) ProtoMessage()    {}
func (*CriarEnderecoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4e4356cce7d54fb, []int{1}
}

func (m *CriarEnderecoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriarEnderecoRequest.Unmarshal(m, b)
}
func (m *CriarEnderecoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriarEnderecoRequest.Marshal(b, m, deterministic)
}
func (m *CriarEnderecoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriarEnderecoRequest.Merge(m, src)
}
func (m *CriarEnderecoRequest) XXX_Size() int {
	return xxx_messageInfo_CriarEnderecoRequest.Size(m)
}
func (m *CriarEnderecoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CriarEnderecoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CriarEnderecoRequest proto.InternalMessageInfo

func (m *CriarEnderecoRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CriarEnderecoRequest) GetEndereco() *Endereco {
	if m != nil {
		return m.Endereco
	}
	return nil
}

// Resposta com ID da pessoa Criada
type CriarEnderecoResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CriarEnderecoResponse) Reset()         { *m = CriarEnderecoResponse{} }
func (m *CriarEnderecoResponse) String() string { return proto.CompactTextString(m) }
func (*CriarEnderecoResponse) ProtoMessage()    {}
func (*CriarEnderecoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4e4356cce7d54fb, []int{2}
}

func (m *CriarEnderecoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriarEnderecoResponse.Unmarshal(m, b)
}
func (m *CriarEnderecoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriarEnderecoResponse.Marshal(b, m, deterministic)
}
func (m *CriarEnderecoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriarEnderecoResponse.Merge(m, src)
}
func (m *CriarEnderecoResponse) XXX_Size() int {
	return xxx_messageInfo_CriarEnderecoResponse.Size(m)
}
func (m *CriarEnderecoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CriarEnderecoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CriarEnderecoResponse proto.InternalMessageInfo

func (m *CriarEnderecoResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CriarEnderecoResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Endereco)(nil), "pessoa.Endereco")
	proto.RegisterType((*CriarEnderecoRequest)(nil), "pessoa.CriarEnderecoRequest")
	proto.RegisterType((*CriarEnderecoResponse)(nil), "pessoa.CriarEnderecoResponse")
}

func init() { proto.RegisterFile("endereco-service.proto", fileDescriptor_c4e4356cce7d54fb) }

var fileDescriptor_c4e4356cce7d54fb = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x95, 0x04, 0x42, 0x7b, 0x15, 0x50, 0x59, 0x50, 0x59, 0x08, 0x50, 0x94, 0xa9, 0x03,
	0x64, 0x28, 0x13, 0x33, 0x62, 0x63, 0x0a, 0x12, 0x2b, 0x72, 0xed, 0x2b, 0xb2, 0xd4, 0xe6, 0x8c,
	0x9d, 0xf0, 0x58, 0x3c, 0x23, 0xb2, 0x5d, 0x57, 0x05, 0x95, 0xed, 0xee, 0xbb, 0x3f, 0xfe, 0xdd,
	0x67, 0x98, 0x61, 0xa7, 0xd0, 0xa2, 0xa4, 0x7b, 0x87, 0xf6, 0x4b, 0x4b, 0x6c, 0x8c, 0xa5, 0x9e,
	0x58, 0x69, 0xd0, 0x39, 0x12, 0xf5, 0x77, 0x06, 0xa3, 0xe7, 0x6d, 0x0b, 0x3b, 0x83, 0x5c, 0x2b,
	0x9e, 0x55, 0xd9, 0xbc, 0x68, 0x73, 0xad, 0xd8, 0x14, 0x0a, 0x89, 0x86, 0xe7, 0x41, 0xf0, 0x21,
	0xbb, 0x05, 0x58, 0xd3, 0x87, 0x15, 0x8a, 0x06, 0x4b, 0xbc, 0xa8, 0xb2, 0xf9, 0xb8, 0xdd, 0x53,
	0x58, 0x05, 0x13, 0x49, 0x1b, 0xb3, 0xc6, 0x0d, 0x76, 0x3d, 0xf1, 0xa3, 0xd0, 0xb0, 0x2f, 0xb1,
	0x19, 0x94, 0x4b, 0xa1, 0xad, 0x25, 0x7e, 0x1c, 0x8a, 0xdb, 0xcc, 0xeb, 0x52, 0x2b, 0xa1, 0x90,
	0x97, 0x51, 0x8f, 0x99, 0x67, 0x1a, 0x56, 0xfc, 0x24, 0x68, 0xf9, 0xb0, 0xaa, 0xdf, 0xe0, 0xe2,
	0xc9, 0x6a, 0x61, 0x13, 0x74, 0x8b, 0x9f, 0x03, 0xba, 0xde, 0xb3, 0x0a, 0xa3, 0x03, 0xfc, 0xb8,
	0xf5, 0x21, 0xbb, 0x83, 0x51, 0x3a, 0x3e, 0x9c, 0x30, 0x59, 0x4c, 0x9b, 0x78, 0x75, 0xb3, 0x1b,
	0xde, 0x75, 0xd4, 0x8f, 0x70, 0xf9, 0x67, 0xaf, 0x33, 0xd4, 0x39, 0x3c, 0xb0, 0x38, 0xda, 0x94,
	0x27, 0x9b, 0x16, 0xef, 0x70, 0x9e, 0xa6, 0x5e, 0xa3, 0xc9, 0xec, 0x05, 0x4e, 0x7f, 0x6d, 0x63,
	0xd7, 0xe9, 0xe9, 0x43, 0xf0, 0x57, 0x37, 0xff, 0x54, 0x23, 0xc2, 0xb2, 0x0c, 0x7f, 0xf6, 0xf0,
	0x13, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x7d, 0x79, 0xb6, 0xcd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EnderecoServiceClient is the client API for EnderecoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EnderecoServiceClient interface {
	// criar endereco
	CriarEndereco(ctx context.Context, in *CriarEnderecoRequest, opts ...grpc.CallOption) (*CriarEnderecoResponse, error)
}

type enderecoServiceClient struct {
	cc *grpc.ClientConn
}

func NewEnderecoServiceClient(cc *grpc.ClientConn) EnderecoServiceClient {
	return &enderecoServiceClient{cc}
}

func (c *enderecoServiceClient) CriarEndereco(ctx context.Context, in *CriarEnderecoRequest, opts ...grpc.CallOption) (*CriarEnderecoResponse, error) {
	out := new(CriarEnderecoResponse)
	err := c.cc.Invoke(ctx, "/pessoa.EnderecoService/CriarEndereco", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnderecoServiceServer is the server API for EnderecoService service.
type EnderecoServiceServer interface {
	// criar endereco
	CriarEndereco(context.Context, *CriarEnderecoRequest) (*CriarEnderecoResponse, error)
}

// UnimplementedEnderecoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEnderecoServiceServer struct {
}

func (*UnimplementedEnderecoServiceServer) CriarEndereco(ctx context.Context, req *CriarEnderecoRequest) (*CriarEnderecoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CriarEndereco not implemented")
}

func RegisterEnderecoServiceServer(s *grpc.Server, srv EnderecoServiceServer) {
	s.RegisterService(&_EnderecoService_serviceDesc, srv)
}

func _EnderecoService_CriarEndereco_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CriarEnderecoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnderecoServiceServer).CriarEndereco(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pessoa.EnderecoService/CriarEndereco",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnderecoServiceServer).CriarEndereco(ctx, req.(*CriarEnderecoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EnderecoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pessoa.EnderecoService",
	HandlerType: (*EnderecoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CriarEndereco",
			Handler:    _EnderecoService_CriarEndereco_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "endereco-service.proto",
}
