// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pessoa-service.proto

package pessoa

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TelefoneTipo int32

const (
	TelefoneTipo_CELULAR  TelefoneTipo = 0
	TelefoneTipo_CASA     TelefoneTipo = 1
	TelefoneTipo_TRABALHO TelefoneTipo = 2
)

var TelefoneTipo_name = map[int32]string{
	0: "CELULAR",
	1: "CASA",
	2: "TRABALHO",
}

var TelefoneTipo_value = map[string]int32{
	"CELULAR":  0,
	"CASA":     1,
	"TRABALHO": 2,
}

func (x TelefoneTipo) String() string {
	return proto.EnumName(TelefoneTipo_name, int32(x))
}

func (TelefoneTipo) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{0}
}

// Objeto Telefone
type Telefone struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Dd                   string       `protobuf:"bytes,2,opt,name=dd,proto3" json:"dd,omitempty"`
	Numero               string       `protobuf:"bytes,3,opt,name=numero,proto3" json:"numero,omitempty"`
	Tipo                 TelefoneTipo `protobuf:"varint,4,opt,name=tipo,proto3,enum=pessoa.TelefoneTipo" json:"tipo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Telefone) Reset()         { *m = Telefone{} }
func (m *Telefone) String() string { return proto.CompactTextString(m) }
func (*Telefone) ProtoMessage()    {}
func (*Telefone) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{0}
}

func (m *Telefone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Telefone.Unmarshal(m, b)
}
func (m *Telefone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Telefone.Marshal(b, m, deterministic)
}
func (m *Telefone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Telefone.Merge(m, src)
}
func (m *Telefone) XXX_Size() int {
	return xxx_messageInfo_Telefone.Size(m)
}
func (m *Telefone) XXX_DiscardUnknown() {
	xxx_messageInfo_Telefone.DiscardUnknown(m)
}

var xxx_messageInfo_Telefone proto.InternalMessageInfo

func (m *Telefone) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Telefone) GetDd() string {
	if m != nil {
		return m.Dd
	}
	return ""
}

func (m *Telefone) GetNumero() string {
	if m != nil {
		return m.Numero
	}
	return ""
}

func (m *Telefone) GetTipo() TelefoneTipo {
	if m != nil {
		return m.Tipo
	}
	return TelefoneTipo_CELULAR
}

// objeto identificador
type Identificador struct {
	Cpf                  int64    `protobuf:"varint,1,opt,name=cpf,proto3" json:"cpf,omitempty"`
	Rg                   int64    `protobuf:"varint,2,opt,name=rg,proto3" json:"rg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identificador) Reset()         { *m = Identificador{} }
func (m *Identificador) String() string { return proto.CompactTextString(m) }
func (*Identificador) ProtoMessage()    {}
func (*Identificador) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{1}
}

func (m *Identificador) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identificador.Unmarshal(m, b)
}
func (m *Identificador) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identificador.Marshal(b, m, deterministic)
}
func (m *Identificador) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identificador.Merge(m, src)
}
func (m *Identificador) XXX_Size() int {
	return xxx_messageInfo_Identificador.Size(m)
}
func (m *Identificador) XXX_DiscardUnknown() {
	xxx_messageInfo_Identificador.DiscardUnknown(m)
}

var xxx_messageInfo_Identificador proto.InternalMessageInfo

func (m *Identificador) GetCpf() int64 {
	if m != nil {
		return m.Cpf
	}
	return 0
}

func (m *Identificador) GetRg() int64 {
	if m != nil {
		return m.Rg
	}
	return 0
}

// Objeto Pessoa
type Pessoa struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome                 string               `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	DtNascimento         *timestamp.Timestamp `protobuf:"bytes,3,opt,name=dtNascimento,proto3" json:"dtNascimento,omitempty"`
	Identificador        []*Identificador     `protobuf:"bytes,4,rep,name=identificador,proto3" json:"identificador,omitempty"`
	Email                string               `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Telefone             []*Telefone          `protobuf:"bytes,6,rep,name=telefone,proto3" json:"telefone,omitempty"`
	Endereco             []*Endereco          `protobuf:"bytes,7,rep,name=endereco,proto3" json:"endereco,omitempty"`
	Reminder             *timestamp.Timestamp `protobuf:"bytes,8,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Pessoa) Reset()         { *m = Pessoa{} }
func (m *Pessoa) String() string { return proto.CompactTextString(m) }
func (*Pessoa) ProtoMessage()    {}
func (*Pessoa) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{2}
}

func (m *Pessoa) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pessoa.Unmarshal(m, b)
}
func (m *Pessoa) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pessoa.Marshal(b, m, deterministic)
}
func (m *Pessoa) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pessoa.Merge(m, src)
}
func (m *Pessoa) XXX_Size() int {
	return xxx_messageInfo_Pessoa.Size(m)
}
func (m *Pessoa) XXX_DiscardUnknown() {
	xxx_messageInfo_Pessoa.DiscardUnknown(m)
}

var xxx_messageInfo_Pessoa proto.InternalMessageInfo

func (m *Pessoa) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pessoa) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

func (m *Pessoa) GetDtNascimento() *timestamp.Timestamp {
	if m != nil {
		return m.DtNascimento
	}
	return nil
}

func (m *Pessoa) GetIdentificador() []*Identificador {
	if m != nil {
		return m.Identificador
	}
	return nil
}

func (m *Pessoa) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Pessoa) GetTelefone() []*Telefone {
	if m != nil {
		return m.Telefone
	}
	return nil
}

func (m *Pessoa) GetEndereco() []*Endereco {
	if m != nil {
		return m.Endereco
	}
	return nil
}

func (m *Pessoa) GetReminder() *timestamp.Timestamp {
	if m != nil {
		return m.Reminder
	}
	return nil
}

// Requisicao para criar uma nova pessoa
type CriarPessoaRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Pessoa               *Pessoa  `protobuf:"bytes,2,opt,name=pessoa,proto3" json:"pessoa,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CriarPessoaRequest) Reset()         { *m = CriarPessoaRequest{} }
func (m *CriarPessoaRequest) String() string { return proto.CompactTextString(m) }
func (*CriarPessoaRequest) ProtoMessage()    {}
func (*CriarPessoaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{3}
}

func (m *CriarPessoaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriarPessoaRequest.Unmarshal(m, b)
}
func (m *CriarPessoaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriarPessoaRequest.Marshal(b, m, deterministic)
}
func (m *CriarPessoaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriarPessoaRequest.Merge(m, src)
}
func (m *CriarPessoaRequest) XXX_Size() int {
	return xxx_messageInfo_CriarPessoaRequest.Size(m)
}
func (m *CriarPessoaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CriarPessoaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CriarPessoaRequest proto.InternalMessageInfo

func (m *CriarPessoaRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CriarPessoaRequest) GetPessoa() *Pessoa {
	if m != nil {
		return m.Pessoa
	}
	return nil
}

// Resposta com ID da pessoa Criada
type CriarPessoaResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CriarPessoaResponse) Reset()         { *m = CriarPessoaResponse{} }
func (m *CriarPessoaResponse) String() string { return proto.CompactTextString(m) }
func (*CriarPessoaResponse) ProtoMessage()    {}
func (*CriarPessoaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{4}
}

func (m *CriarPessoaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriarPessoaResponse.Unmarshal(m, b)
}
func (m *CriarPessoaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriarPessoaResponse.Marshal(b, m, deterministic)
}
func (m *CriarPessoaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriarPessoaResponse.Merge(m, src)
}
func (m *CriarPessoaResponse) XXX_Size() int {
	return xxx_messageInfo_CriarPessoaResponse.Size(m)
}
func (m *CriarPessoaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CriarPessoaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CriarPessoaResponse proto.InternalMessageInfo

func (m *CriarPessoaResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CriarPessoaResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

//CriarIdentificadorResponse cria um identificador para a pessoa response
type CriarIdentificadorResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Cpf                  int64    `protobuf:"varint,2,opt,name=cpf,proto3" json:"cpf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CriarIdentificadorResponse) Reset()         { *m = CriarIdentificadorResponse{} }
func (m *CriarIdentificadorResponse) String() string { return proto.CompactTextString(m) }
func (*CriarIdentificadorResponse) ProtoMessage()    {}
func (*CriarIdentificadorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{5}
}

func (m *CriarIdentificadorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriarIdentificadorResponse.Unmarshal(m, b)
}
func (m *CriarIdentificadorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriarIdentificadorResponse.Marshal(b, m, deterministic)
}
func (m *CriarIdentificadorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriarIdentificadorResponse.Merge(m, src)
}
func (m *CriarIdentificadorResponse) XXX_Size() int {
	return xxx_messageInfo_CriarIdentificadorResponse.Size(m)
}
func (m *CriarIdentificadorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CriarIdentificadorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CriarIdentificadorResponse proto.InternalMessageInfo

func (m *CriarIdentificadorResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CriarIdentificadorResponse) GetCpf() int64 {
	if m != nil {
		return m.Cpf
	}
	return 0
}

//CriarIdentificadorRequest cria um identificador para a pessoa request
type CriarIdentificadorRequest struct {
	Identificador        *Identificador `protobuf:"bytes,1,opt,name=identificador,proto3" json:"identificador,omitempty"`
	Api                  string         `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CriarIdentificadorRequest) Reset()         { *m = CriarIdentificadorRequest{} }
func (m *CriarIdentificadorRequest) String() string { return proto.CompactTextString(m) }
func (*CriarIdentificadorRequest) ProtoMessage()    {}
func (*CriarIdentificadorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{6}
}

func (m *CriarIdentificadorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriarIdentificadorRequest.Unmarshal(m, b)
}
func (m *CriarIdentificadorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriarIdentificadorRequest.Marshal(b, m, deterministic)
}
func (m *CriarIdentificadorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriarIdentificadorRequest.Merge(m, src)
}
func (m *CriarIdentificadorRequest) XXX_Size() int {
	return xxx_messageInfo_CriarIdentificadorRequest.Size(m)
}
func (m *CriarIdentificadorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CriarIdentificadorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CriarIdentificadorRequest proto.InternalMessageInfo

func (m *CriarIdentificadorRequest) GetIdentificador() *Identificador {
	if m != nil {
		return m.Identificador
	}
	return nil
}

func (m *CriarIdentificadorRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

//CriarTelefoneResponse cria um telefone para a pessoa response
type CriarTelefoneResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CriarTelefoneResponse) Reset()         { *m = CriarTelefoneResponse{} }
func (m *CriarTelefoneResponse) String() string { return proto.CompactTextString(m) }
func (*CriarTelefoneResponse) ProtoMessage()    {}
func (*CriarTelefoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{7}
}

func (m *CriarTelefoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriarTelefoneResponse.Unmarshal(m, b)
}
func (m *CriarTelefoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriarTelefoneResponse.Marshal(b, m, deterministic)
}
func (m *CriarTelefoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriarTelefoneResponse.Merge(m, src)
}
func (m *CriarTelefoneResponse) XXX_Size() int {
	return xxx_messageInfo_CriarTelefoneResponse.Size(m)
}
func (m *CriarTelefoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CriarTelefoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CriarTelefoneResponse proto.InternalMessageInfo

func (m *CriarTelefoneResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CriarTelefoneResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

//CriarTelefoneRequest cria um telefone para a pessoa request
type CriarTelefoneRequest struct {
	Telefone             *Telefone `protobuf:"bytes,1,opt,name=telefone,proto3" json:"telefone,omitempty"`
	Api                  string    `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CriarTelefoneRequest) Reset()         { *m = CriarTelefoneRequest{} }
func (m *CriarTelefoneRequest) String() string { return proto.CompactTextString(m) }
func (*CriarTelefoneRequest) ProtoMessage()    {}
func (*CriarTelefoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{8}
}

func (m *CriarTelefoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriarTelefoneRequest.Unmarshal(m, b)
}
func (m *CriarTelefoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriarTelefoneRequest.Marshal(b, m, deterministic)
}
func (m *CriarTelefoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriarTelefoneRequest.Merge(m, src)
}
func (m *CriarTelefoneRequest) XXX_Size() int {
	return xxx_messageInfo_CriarTelefoneRequest.Size(m)
}
func (m *CriarTelefoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CriarTelefoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CriarTelefoneRequest proto.InternalMessageInfo

func (m *CriarTelefoneRequest) GetTelefone() *Telefone {
	if m != nil {
		return m.Telefone
	}
	return nil
}

func (m *CriarTelefoneRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func init() {
	proto.RegisterEnum("pessoa.TelefoneTipo", TelefoneTipo_name, TelefoneTipo_value)
	proto.RegisterType((*Telefone)(nil), "pessoa.Telefone")
	proto.RegisterType((*Identificador)(nil), "pessoa.Identificador")
	proto.RegisterType((*Pessoa)(nil), "pessoa.Pessoa")
	proto.RegisterType((*CriarPessoaRequest)(nil), "pessoa.CriarPessoaRequest")
	proto.RegisterType((*CriarPessoaResponse)(nil), "pessoa.CriarPessoaResponse")
	proto.RegisterType((*CriarIdentificadorResponse)(nil), "pessoa.CriarIdentificadorResponse")
	proto.RegisterType((*CriarIdentificadorRequest)(nil), "pessoa.CriarIdentificadorRequest")
	proto.RegisterType((*CriarTelefoneResponse)(nil), "pessoa.CriarTelefoneResponse")
	proto.RegisterType((*CriarTelefoneRequest)(nil), "pessoa.CriarTelefoneRequest")
}

func init() { proto.RegisterFile("pessoa-service.proto", fileDescriptor_3daf7753e5a8644f) }

var fileDescriptor_3daf7753e5a8644f = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xd1, 0x6e, 0xd3, 0x3c,
	0x18, 0xfd, 0xe3, 0x76, 0x5d, 0xf6, 0x75, 0xad, 0x2a, 0xff, 0xed, 0x14, 0xc2, 0x10, 0x25, 0x17,
	0xa8, 0x9a, 0x20, 0x15, 0x9d, 0x04, 0x02, 0x24, 0xb4, 0x52, 0x4d, 0x02, 0xa9, 0x1a, 0x93, 0x57,
	0xb8, 0xcf, 0x12, 0xb7, 0x32, 0x6a, 0xe2, 0x90, 0xb8, 0xdc, 0x71, 0xc3, 0x2b, 0x70, 0xcf, 0x4b,
	0xed, 0x15, 0x78, 0x10, 0x14, 0xdb, 0x89, 0xea, 0xb6, 0x1b, 0xbb, 0x8b, 0xed, 0xe3, 0xf3, 0x9d,
	0xef, 0x9c, 0xcf, 0x81, 0x6e, 0x4a, 0xf3, 0x9c, 0x07, 0xcf, 0x73, 0x9a, 0x7d, 0x67, 0x21, 0xf5,
	0xd3, 0x8c, 0x0b, 0x8e, 0x1b, 0x6a, 0xd7, 0x7d, 0xbc, 0xe0, 0x7c, 0xb1, 0xa4, 0x43, 0xb9, 0x7b,
	0xbd, 0x9a, 0x0f, 0x05, 0x8b, 0x69, 0x2e, 0x82, 0x38, 0x55, 0x40, 0xf7, 0x58, 0x03, 0x82, 0x94,
	0x0d, 0x83, 0x24, 0xe1, 0x22, 0x10, 0x8c, 0x27, 0xb9, 0x3e, 0x3d, 0xa2, 0x49, 0x44, 0x33, 0x1a,
	0x72, 0x93, 0xde, 0x5b, 0x82, 0x3d, 0xa3, 0x4b, 0x3a, 0xe7, 0x09, 0xc5, 0x6d, 0x40, 0x2c, 0x72,
	0xac, 0xbe, 0x35, 0xa8, 0x11, 0xc4, 0xa2, 0x62, 0x1d, 0x45, 0x0e, 0xea, 0x5b, 0x83, 0x03, 0x82,
	0xa2, 0x08, 0x1f, 0x41, 0x23, 0x59, 0xc5, 0x34, 0xe3, 0x4e, 0x4d, 0xee, 0xe9, 0x15, 0x1e, 0x40,
	0x5d, 0xb0, 0x94, 0x3b, 0xf5, 0xbe, 0x35, 0x68, 0x8f, 0xba, 0xbe, 0x52, 0xec, 0x97, 0xbc, 0x33,
	0x96, 0x72, 0x22, 0x11, 0xde, 0x0b, 0x68, 0x7d, 0x8c, 0x68, 0x22, 0xd8, 0x9c, 0x85, 0x41, 0xc4,
	0x33, 0xdc, 0x81, 0x5a, 0x98, 0xce, 0x75, 0xcd, 0xe2, 0xb3, 0x28, 0x9a, 0x2d, 0x64, 0xd1, 0x1a,
	0x41, 0xd9, 0xc2, 0xbb, 0x41, 0xd0, 0xb8, 0x94, 0x84, 0x5b, 0xfa, 0x30, 0xd4, 0x13, 0x1e, 0x53,
	0xad, 0x50, 0x7e, 0xe3, 0x77, 0x70, 0x18, 0x89, 0x8b, 0x20, 0x0f, 0x59, 0x4c, 0x13, 0xa1, 0x94,
	0x36, 0x47, 0xae, 0xaf, 0xcc, 0xf1, 0x4b, 0xf7, 0xfc, 0x59, 0xe9, 0x1e, 0x31, 0xf0, 0xf8, 0x2d,
	0xb4, 0xd8, 0xba, 0x42, 0xa7, 0xde, 0xaf, 0x0d, 0x9a, 0xa3, 0x5e, 0xd9, 0x94, 0x21, 0x9f, 0x98,
	0x58, 0xdc, 0x85, 0x3d, 0x1a, 0x07, 0x6c, 0xe9, 0xec, 0x49, 0x45, 0x6a, 0x81, 0x9f, 0x81, 0x2d,
	0xb4, 0x15, 0x4e, 0x43, 0xb2, 0x75, 0x36, 0x2d, 0x22, 0x15, 0xa2, 0x40, 0x97, 0x51, 0x39, 0xfb,
	0x26, 0xfa, 0x5c, 0xef, 0x93, 0x0a, 0x81, 0x5f, 0x82, 0x9d, 0xd1, 0x98, 0x15, 0x4b, 0xc7, 0xfe,
	0x67, 0xab, 0x15, 0xd6, 0xbb, 0x00, 0x3c, 0xc9, 0x58, 0x90, 0x29, 0x67, 0x09, 0xfd, 0xb6, 0xa2,
	0xb9, 0x28, 0xd2, 0x08, 0x52, 0x26, 0x1d, 0x3e, 0x20, 0xc5, 0x27, 0x7e, 0x0a, 0x7a, 0xfe, 0xa4,
	0xc9, 0xcd, 0x51, 0xbb, 0xd4, 0xa2, 0x2f, 0xea, 0x53, 0xef, 0x15, 0xfc, 0x6f, 0xf0, 0xe5, 0x29,
	0x4f, 0x72, 0xba, 0x83, 0x50, 0x65, 0x88, 0xca, 0x0c, 0xbd, 0x33, 0x70, 0xe5, 0x45, 0xd3, 0xd7,
	0xdb, 0xef, 0xeb, 0x81, 0x41, 0xd5, 0xc0, 0x78, 0x5f, 0xe1, 0xc1, 0x2e, 0x06, 0xd5, 0xd1, 0x56,
	0x9c, 0x96, 0x6c, 0xe3, 0x7e, 0x71, 0xea, 0xea, 0xa8, 0xaa, 0xee, 0xbd, 0x86, 0x9e, 0xac, 0x55,
	0xe5, 0x76, 0xff, 0x46, 0xbf, 0x40, 0x77, 0xe3, 0xaa, 0x52, 0xb8, 0x3e, 0x1d, 0x4a, 0xdc, 0x5d,
	0xd3, 0xb1, 0x25, 0xe9, 0xe4, 0x14, 0x0e, 0xd7, 0x1f, 0x1a, 0x6e, 0xc2, 0xfe, 0xe4, 0x7c, 0xfa,
	0x79, 0x3a, 0x26, 0x9d, 0xff, 0xb0, 0x0d, 0xf5, 0xc9, 0xf8, 0x6a, 0xdc, 0xb1, 0xf0, 0x21, 0xd8,
	0x33, 0x32, 0x7e, 0x3f, 0x9e, 0x7e, 0xf8, 0xd4, 0x41, 0xa3, 0xdf, 0x08, 0x5a, 0x2a, 0xaa, 0x2b,
	0xf5, 0x37, 0xc0, 0x67, 0xb0, 0x17, 0x16, 0xf2, 0xb0, 0x5b, 0x56, 0xdf, 0x9e, 0x0f, 0xf7, 0xe1,
	0xce, 0x33, 0x6d, 0xc1, 0x0f, 0x3d, 0x52, 0xe6, 0x03, 0x7f, 0x62, 0x5c, 0xd9, 0x95, 0x91, 0xeb,
	0xdd, 0x05, 0x51, 0xe4, 0x5e, 0xff, 0xe7, 0xcd, 0x9f, 0x5f, 0xc8, 0xf5, 0x7a, 0x43, 0x85, 0x1d,
	0x1a, 0x49, 0xbd, 0xb1, 0x4e, 0xf0, 0x14, 0x5a, 0x86, 0xbf, 0xf8, 0xd8, 0xa0, 0xdd, 0xb0, 0xdd,
	0x7d, 0x74, 0xcb, 0xa9, 0xaa, 0x77, 0x89, 0xae, 0x1b, 0xf2, 0xfd, 0x9c, 0xfe, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0x5c, 0x4f, 0x87, 0xfd, 0x96, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PessoaServiceClient is the client API for PessoaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PessoaServiceClient interface {
	// Cria uma nova pessoa
	Criar(ctx context.Context, in *CriarPessoaRequest, opts ...grpc.CallOption) (*CriarPessoaResponse, error)
	//cria o identificador da pessoa
	CriarIdentificador(ctx context.Context, in *CriarIdentificadorRequest, opts ...grpc.CallOption) (*CriarIdentificadorResponse, error)
	// cria o telefone da pessoa
	CriarTelefone(ctx context.Context, in *CriarTelefoneRequest, opts ...grpc.CallOption) (*CriarTelefoneResponse, error)
}

type pessoaServiceClient struct {
	cc *grpc.ClientConn
}

func NewPessoaServiceClient(cc *grpc.ClientConn) PessoaServiceClient {
	return &pessoaServiceClient{cc}
}

func (c *pessoaServiceClient) Criar(ctx context.Context, in *CriarPessoaRequest, opts ...grpc.CallOption) (*CriarPessoaResponse, error) {
	out := new(CriarPessoaResponse)
	err := c.cc.Invoke(ctx, "/pessoa.PessoaService/criar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pessoaServiceClient) CriarIdentificador(ctx context.Context, in *CriarIdentificadorRequest, opts ...grpc.CallOption) (*CriarIdentificadorResponse, error) {
	out := new(CriarIdentificadorResponse)
	err := c.cc.Invoke(ctx, "/pessoa.PessoaService/CriarIdentificador", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pessoaServiceClient) CriarTelefone(ctx context.Context, in *CriarTelefoneRequest, opts ...grpc.CallOption) (*CriarTelefoneResponse, error) {
	out := new(CriarTelefoneResponse)
	err := c.cc.Invoke(ctx, "/pessoa.PessoaService/CriarTelefone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PessoaServiceServer is the server API for PessoaService service.
type PessoaServiceServer interface {
	// Cria uma nova pessoa
	Criar(context.Context, *CriarPessoaRequest) (*CriarPessoaResponse, error)
	//cria o identificador da pessoa
	CriarIdentificador(context.Context, *CriarIdentificadorRequest) (*CriarIdentificadorResponse, error)
	// cria o telefone da pessoa
	CriarTelefone(context.Context, *CriarTelefoneRequest) (*CriarTelefoneResponse, error)
}

// UnimplementedPessoaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPessoaServiceServer struct {
}

func (*UnimplementedPessoaServiceServer) Criar(ctx context.Context, req *CriarPessoaRequest) (*CriarPessoaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Criar not implemented")
}
func (*UnimplementedPessoaServiceServer) CriarIdentificador(ctx context.Context, req *CriarIdentificadorRequest) (*CriarIdentificadorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CriarIdentificador not implemented")
}
func (*UnimplementedPessoaServiceServer) CriarTelefone(ctx context.Context, req *CriarTelefoneRequest) (*CriarTelefoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CriarTelefone not implemented")
}

func RegisterPessoaServiceServer(s *grpc.Server, srv PessoaServiceServer) {
	s.RegisterService(&_PessoaService_serviceDesc, srv)
}

func _PessoaService_Criar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CriarPessoaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PessoaServiceServer).Criar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pessoa.PessoaService/Criar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PessoaServiceServer).Criar(ctx, req.(*CriarPessoaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PessoaService_CriarIdentificador_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CriarIdentificadorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PessoaServiceServer).CriarIdentificador(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pessoa.PessoaService/CriarIdentificador",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PessoaServiceServer).CriarIdentificador(ctx, req.(*CriarIdentificadorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PessoaService_CriarTelefone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CriarTelefoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PessoaServiceServer).CriarTelefone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pessoa.PessoaService/CriarTelefone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PessoaServiceServer).CriarTelefone(ctx, req.(*CriarTelefoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PessoaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pessoa.PessoaService",
	HandlerType: (*PessoaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "criar",
			Handler:    _PessoaService_Criar_Handler,
		},
		{
			MethodName: "CriarIdentificador",
			Handler:    _PessoaService_CriarIdentificador_Handler,
		},
		{
			MethodName: "CriarTelefone",
			Handler:    _PessoaService_CriarTelefone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pessoa-service.proto",
}
