// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pessoa-service.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Telefone_TelefoneTipo int32

const (
	Telefone_CELULAR  Telefone_TelefoneTipo = 0
	Telefone_CASA     Telefone_TelefoneTipo = 1
	Telefone_TRABALHO Telefone_TelefoneTipo = 2
)

var Telefone_TelefoneTipo_name = map[int32]string{
	0: "CELULAR",
	1: "CASA",
	2: "TRABALHO",
}

var Telefone_TelefoneTipo_value = map[string]int32{
	"CELULAR":  0,
	"CASA":     1,
	"TRABALHO": 2,
}

func (x Telefone_TelefoneTipo) String() string {
	return proto.EnumName(Telefone_TelefoneTipo_name, int32(x))
}

func (Telefone_TelefoneTipo) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{0, 0}
}

// Objeto Telefone
type Telefone struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Dd                   string                `protobuf:"bytes,2,opt,name=dd,proto3" json:"dd,omitempty"`
	Numero               string                `protobuf:"bytes,3,opt,name=numero,proto3" json:"numero,omitempty"`
	Tipo                 Telefone_TelefoneTipo `protobuf:"varint,4,opt,name=tipo,proto3,enum=user.Telefone_TelefoneTipo" json:"tipo,omitempty"`
	Reminder             *timestamp.Timestamp  `protobuf:"bytes,5,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Telefone) Reset()         { *m = Telefone{} }
func (m *Telefone) String() string { return proto.CompactTextString(m) }
func (*Telefone) ProtoMessage()    {}
func (*Telefone) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{0}
}

func (m *Telefone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Telefone.Unmarshal(m, b)
}
func (m *Telefone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Telefone.Marshal(b, m, deterministic)
}
func (m *Telefone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Telefone.Merge(m, src)
}
func (m *Telefone) XXX_Size() int {
	return xxx_messageInfo_Telefone.Size(m)
}
func (m *Telefone) XXX_DiscardUnknown() {
	xxx_messageInfo_Telefone.DiscardUnknown(m)
}

var xxx_messageInfo_Telefone proto.InternalMessageInfo

func (m *Telefone) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Telefone) GetDd() string {
	if m != nil {
		return m.Dd
	}
	return ""
}

func (m *Telefone) GetNumero() string {
	if m != nil {
		return m.Numero
	}
	return ""
}

func (m *Telefone) GetTipo() Telefone_TelefoneTipo {
	if m != nil {
		return m.Tipo
	}
	return Telefone_CELULAR
}

func (m *Telefone) GetReminder() *timestamp.Timestamp {
	if m != nil {
		return m.Reminder
	}
	return nil
}

// objeto identificador
type Identificador struct {
	Cpf                  int64                `protobuf:"varint,1,opt,name=cpf,proto3" json:"cpf,omitempty"`
	Rg                   int64                `protobuf:"varint,2,opt,name=rg,proto3" json:"rg,omitempty"`
	Reminder             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Identificador) Reset()         { *m = Identificador{} }
func (m *Identificador) String() string { return proto.CompactTextString(m) }
func (*Identificador) ProtoMessage()    {}
func (*Identificador) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{1}
}

func (m *Identificador) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identificador.Unmarshal(m, b)
}
func (m *Identificador) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identificador.Marshal(b, m, deterministic)
}
func (m *Identificador) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identificador.Merge(m, src)
}
func (m *Identificador) XXX_Size() int {
	return xxx_messageInfo_Identificador.Size(m)
}
func (m *Identificador) XXX_DiscardUnknown() {
	xxx_messageInfo_Identificador.DiscardUnknown(m)
}

var xxx_messageInfo_Identificador proto.InternalMessageInfo

func (m *Identificador) GetCpf() int64 {
	if m != nil {
		return m.Cpf
	}
	return 0
}

func (m *Identificador) GetRg() int64 {
	if m != nil {
		return m.Rg
	}
	return 0
}

func (m *Identificador) GetReminder() *timestamp.Timestamp {
	if m != nil {
		return m.Reminder
	}
	return nil
}

//Objeto Endereço
type Endereco struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cep                  int64                `protobuf:"varint,2,opt,name=cep,proto3" json:"cep,omitempty"`
	Logradouro           string               `protobuf:"bytes,3,opt,name=logradouro,proto3" json:"logradouro,omitempty"`
	Complemento          string               `protobuf:"bytes,4,opt,name=complemento,proto3" json:"complemento,omitempty"`
	Bairro               string               `protobuf:"bytes,5,opt,name=bairro,proto3" json:"bairro,omitempty"`
	Cidade               string               `protobuf:"bytes,6,opt,name=cidade,proto3" json:"cidade,omitempty"`
	Uf                   string               `protobuf:"bytes,7,opt,name=uf,proto3" json:"uf,omitempty"`
	Reminder             *timestamp.Timestamp `protobuf:"bytes,8,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Endereco) Reset()         { *m = Endereco{} }
func (m *Endereco) String() string { return proto.CompactTextString(m) }
func (*Endereco) ProtoMessage()    {}
func (*Endereco) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{2}
}

func (m *Endereco) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endereco.Unmarshal(m, b)
}
func (m *Endereco) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endereco.Marshal(b, m, deterministic)
}
func (m *Endereco) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endereco.Merge(m, src)
}
func (m *Endereco) XXX_Size() int {
	return xxx_messageInfo_Endereco.Size(m)
}
func (m *Endereco) XXX_DiscardUnknown() {
	xxx_messageInfo_Endereco.DiscardUnknown(m)
}

var xxx_messageInfo_Endereco proto.InternalMessageInfo

func (m *Endereco) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Endereco) GetCep() int64 {
	if m != nil {
		return m.Cep
	}
	return 0
}

func (m *Endereco) GetLogradouro() string {
	if m != nil {
		return m.Logradouro
	}
	return ""
}

func (m *Endereco) GetComplemento() string {
	if m != nil {
		return m.Complemento
	}
	return ""
}

func (m *Endereco) GetBairro() string {
	if m != nil {
		return m.Bairro
	}
	return ""
}

func (m *Endereco) GetCidade() string {
	if m != nil {
		return m.Cidade
	}
	return ""
}

func (m *Endereco) GetUf() string {
	if m != nil {
		return m.Uf
	}
	return ""
}

func (m *Endereco) GetReminder() *timestamp.Timestamp {
	if m != nil {
		return m.Reminder
	}
	return nil
}

// Objeto Pessoa
type Pessoa struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome                 string               `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	DtNascimento         int64                `protobuf:"varint,3,opt,name=dtNascimento,proto3" json:"dtNascimento,omitempty"`
	Identificador        []*Identificador     `protobuf:"bytes,4,rep,name=identificador,proto3" json:"identificador,omitempty"`
	Email                string               `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Telefone             []*Telefone          `protobuf:"bytes,6,rep,name=telefone,proto3" json:"telefone,omitempty"`
	Endereco             []*Endereco          `protobuf:"bytes,7,rep,name=endereco,proto3" json:"endereco,omitempty"`
	Reminder             *timestamp.Timestamp `protobuf:"bytes,8,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Pessoa) Reset()         { *m = Pessoa{} }
func (m *Pessoa) String() string { return proto.CompactTextString(m) }
func (*Pessoa) ProtoMessage()    {}
func (*Pessoa) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{3}
}

func (m *Pessoa) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pessoa.Unmarshal(m, b)
}
func (m *Pessoa) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pessoa.Marshal(b, m, deterministic)
}
func (m *Pessoa) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pessoa.Merge(m, src)
}
func (m *Pessoa) XXX_Size() int {
	return xxx_messageInfo_Pessoa.Size(m)
}
func (m *Pessoa) XXX_DiscardUnknown() {
	xxx_messageInfo_Pessoa.DiscardUnknown(m)
}

var xxx_messageInfo_Pessoa proto.InternalMessageInfo

func (m *Pessoa) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pessoa) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

func (m *Pessoa) GetDtNascimento() int64 {
	if m != nil {
		return m.DtNascimento
	}
	return 0
}

func (m *Pessoa) GetIdentificador() []*Identificador {
	if m != nil {
		return m.Identificador
	}
	return nil
}

func (m *Pessoa) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Pessoa) GetTelefone() []*Telefone {
	if m != nil {
		return m.Telefone
	}
	return nil
}

func (m *Pessoa) GetEndereco() []*Endereco {
	if m != nil {
		return m.Endereco
	}
	return nil
}

func (m *Pessoa) GetReminder() *timestamp.Timestamp {
	if m != nil {
		return m.Reminder
	}
	return nil
}

// Requisicao para criar uma nova pessoa
type CrearPessoaRequest struct {
	Pessoa               *Pessoa  `protobuf:"bytes,1,opt,name=pessoa,proto3" json:"pessoa,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrearPessoaRequest) Reset()         { *m = CrearPessoaRequest{} }
func (m *CrearPessoaRequest) String() string { return proto.CompactTextString(m) }
func (*CrearPessoaRequest) ProtoMessage()    {}
func (*CrearPessoaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{4}
}

func (m *CrearPessoaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrearPessoaRequest.Unmarshal(m, b)
}
func (m *CrearPessoaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrearPessoaRequest.Marshal(b, m, deterministic)
}
func (m *CrearPessoaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrearPessoaRequest.Merge(m, src)
}
func (m *CrearPessoaRequest) XXX_Size() int {
	return xxx_messageInfo_CrearPessoaRequest.Size(m)
}
func (m *CrearPessoaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrearPessoaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrearPessoaRequest proto.InternalMessageInfo

func (m *CrearPessoaRequest) GetPessoa() *Pessoa {
	if m != nil {
		return m.Pessoa
	}
	return nil
}

// Resposta com ID da pessoa Criada
type CrearPessoaResponse struct {
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrearPessoaResponse) Reset()         { *m = CrearPessoaResponse{} }
func (m *CrearPessoaResponse) String() string { return proto.CompactTextString(m) }
func (*CrearPessoaResponse) ProtoMessage()    {}
func (*CrearPessoaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3daf7753e5a8644f, []int{5}
}

func (m *CrearPessoaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrearPessoaResponse.Unmarshal(m, b)
}
func (m *CrearPessoaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrearPessoaResponse.Marshal(b, m, deterministic)
}
func (m *CrearPessoaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrearPessoaResponse.Merge(m, src)
}
func (m *CrearPessoaResponse) XXX_Size() int {
	return xxx_messageInfo_CrearPessoaResponse.Size(m)
}
func (m *CrearPessoaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrearPessoaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrearPessoaResponse proto.InternalMessageInfo

func (m *CrearPessoaResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("user.Telefone_TelefoneTipo", Telefone_TelefoneTipo_name, Telefone_TelefoneTipo_value)
	proto.RegisterType((*Telefone)(nil), "user.Telefone")
	proto.RegisterType((*Identificador)(nil), "user.Identificador")
	proto.RegisterType((*Endereco)(nil), "user.Endereco")
	proto.RegisterType((*Pessoa)(nil), "user.Pessoa")
	proto.RegisterType((*CrearPessoaRequest)(nil), "user.CrearPessoaRequest")
	proto.RegisterType((*CrearPessoaResponse)(nil), "user.CrearPessoaResponse")
}

func init() { proto.RegisterFile("pessoa-service.proto", fileDescriptor_3daf7753e5a8644f) }

var fileDescriptor_3daf7753e5a8644f = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x6d, 0x8b, 0xd3, 0x40,
	0x10, 0x36, 0x2f, 0x97, 0xcb, 0x4d, 0x5f, 0x28, 0x7b, 0x87, 0xac, 0x15, 0x34, 0x14, 0x85, 0x22,
	0x98, 0x42, 0x0f, 0x04, 0xc5, 0x2f, 0xb5, 0x1c, 0x28, 0xd4, 0x17, 0xf6, 0xea, 0x0f, 0x48, 0xb3,
	0x93, 0xb2, 0xd0, 0x64, 0xe3, 0x26, 0xf1, 0x7f, 0xf9, 0x8f, 0xfc, 0xe4, 0xef, 0x90, 0xdd, 0x4d,
	0x4a, 0x43, 0xfd, 0x72, 0x7e, 0x9b, 0x97, 0x27, 0x33, 0xf3, 0x3c, 0x33, 0x1b, 0xb8, 0x29, 0xb1,
	0xaa, 0x64, 0xf2, 0xba, 0x42, 0xf5, 0x53, 0xa4, 0x18, 0x97, 0x4a, 0xd6, 0x92, 0xf8, 0x4d, 0x85,
	0x6a, 0xfa, 0x7c, 0x2f, 0xe5, 0xfe, 0x80, 0x0b, 0x13, 0xdb, 0x35, 0xd9, 0xa2, 0x16, 0x39, 0x56,
	0x75, 0x92, 0x97, 0x16, 0x36, 0xfb, 0xed, 0x40, 0xb8, 0xc5, 0x03, 0x66, 0xb2, 0x40, 0x32, 0x06,
	0x57, 0x70, 0xea, 0x44, 0xce, 0xdc, 0x63, 0xae, 0xe0, 0xda, 0xe7, 0x9c, 0xba, 0x91, 0x33, 0xbf,
	0x62, 0x2e, 0xe7, 0xe4, 0x31, 0x04, 0x45, 0x93, 0xa3, 0x92, 0xd4, 0x33, 0xb1, 0xd6, 0x23, 0x0b,
	0xf0, 0x6b, 0x51, 0x4a, 0xea, 0x47, 0xce, 0x7c, 0xbc, 0x7c, 0x1a, 0xeb, 0xd6, 0x71, 0x57, 0xf5,
	0x68, 0x6c, 0x45, 0x29, 0x99, 0x01, 0x92, 0x37, 0x10, 0x2a, 0xcc, 0x45, 0xc1, 0x51, 0xd1, 0x8b,
	0xc8, 0x99, 0x0f, 0x96, 0xd3, 0xd8, 0x4e, 0x1a, 0x77, 0x93, 0xc6, 0xdb, 0x6e, 0x52, 0x76, 0xc4,
	0xce, 0x6e, 0x61, 0x78, 0x5a, 0x8d, 0x0c, 0xe0, 0x72, 0x7d, 0xb7, 0xf9, 0xbe, 0x59, 0xb1, 0xc9,
	0x23, 0x12, 0x82, 0xbf, 0x5e, 0xdd, 0xaf, 0x26, 0x0e, 0x19, 0x42, 0xb8, 0x65, 0xab, 0x0f, 0xab,
	0xcd, 0xc7, 0xaf, 0x13, 0x77, 0x26, 0x60, 0xf4, 0x89, 0x63, 0x51, 0x8b, 0x4c, 0xa4, 0x09, 0x97,
	0x8a, 0x4c, 0xc0, 0x4b, 0xcb, 0xac, 0xe5, 0xa9, 0x4d, 0x4d, 0x54, 0xed, 0x0d, 0x51, 0x8f, 0xb9,
	0x6a, 0xdf, 0x9b, 0xcf, 0x7f, 0xc0, 0x7c, 0x7f, 0x1c, 0x08, 0xef, 0xb4, 0x85, 0xa9, 0x3c, 0x53,
	0x53, 0xb7, 0xc5, 0xb2, 0xed, 0xa2, 0x4d, 0xf2, 0x0c, 0xe0, 0x20, 0xf7, 0x2a, 0xe1, 0xb2, 0x39,
	0x6a, 0x7a, 0x12, 0x21, 0x11, 0x0c, 0x52, 0x99, 0x97, 0x07, 0xcc, 0xb1, 0xa8, 0xad, 0xbc, 0x57,
	0xec, 0x34, 0xa4, 0x37, 0xb2, 0x4b, 0x84, 0x52, 0xd2, 0xc8, 0x78, 0xc5, 0x5a, 0x4f, 0xc7, 0x53,
	0xc1, 0x13, 0x8e, 0x34, 0xb0, 0x71, 0xeb, 0xe9, 0x99, 0x9a, 0x8c, 0x5e, 0xda, 0x8d, 0x36, 0x59,
	0x8f, 0x68, 0xf8, 0x00, 0xa2, 0xbf, 0x5c, 0x08, 0xbe, 0x99, 0xb3, 0x3b, 0xa3, 0x49, 0xc0, 0x2f,
	0x64, 0x8e, 0xed, 0xd9, 0x18, 0x9b, 0xcc, 0x60, 0xc8, 0xeb, 0x2f, 0x49, 0x95, 0x0a, 0xcb, 0xc4,
	0x33, 0xe8, 0x5e, 0x8c, 0xbc, 0x85, 0x91, 0x38, 0x5d, 0x13, 0xf5, 0x23, 0x6f, 0x3e, 0x58, 0x5e,
	0xdb, 0x6b, 0xea, 0x6d, 0x90, 0xf5, 0x91, 0xe4, 0x06, 0x2e, 0x30, 0x4f, 0xc4, 0xa1, 0x15, 0xc1,
	0x3a, 0xe4, 0x15, 0x84, 0x75, 0x7b, 0x2c, 0x34, 0x30, 0xb5, 0xc6, 0xfd, 0xcb, 0x64, 0xc7, 0xbc,
	0xc6, 0x62, 0xbb, 0x37, 0x7a, 0x79, 0x8a, 0xed, 0xb6, 0xc9, 0x8e, 0xf9, 0xff, 0xd6, 0xec, 0x1d,
	0x90, 0xb5, 0xc2, 0x44, 0x59, 0xdd, 0x18, 0xfe, 0x68, 0xb0, 0xaa, 0xc9, 0x0b, 0x08, 0xec, 0xfb,
	0x35, 0x12, 0x0e, 0x96, 0x43, 0xdb, 0xb7, 0x05, 0xb5, 0xb9, 0xd9, 0x4b, 0xb8, 0xee, 0x7d, 0x5b,
	0x95, 0xb2, 0xa8, 0xba, 0x07, 0xeb, 0x76, 0xda, 0x2f, 0x3f, 0xc3, 0xc8, 0x22, 0xee, 0xed, 0xbf,
	0x80, 0xbc, 0x87, 0x8b, 0x54, 0x89, 0x44, 0x11, 0x6a, 0xcb, 0x9e, 0x0f, 0x30, 0x7d, 0xf2, 0x8f,
	0x8c, 0x2d, 0xbf, 0x0b, 0x0c, 0x9f, 0xdb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x16, 0xeb, 0xc2,
	0x5f, 0x62, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PessoaServiceClient is the client API for PessoaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PessoaServiceClient interface {
	// Cria uma nova pessoa
	Criar(ctx context.Context, in *CrearPessoaRequest, opts ...grpc.CallOption) (*CrearPessoaResponse, error)
}

type pessoaServiceClient struct {
	cc *grpc.ClientConn
}

func NewPessoaServiceClient(cc *grpc.ClientConn) PessoaServiceClient {
	return &pessoaServiceClient{cc}
}

func (c *pessoaServiceClient) Criar(ctx context.Context, in *CrearPessoaRequest, opts ...grpc.CallOption) (*CrearPessoaResponse, error) {
	out := new(CrearPessoaResponse)
	err := c.cc.Invoke(ctx, "/user.PessoaService/criar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PessoaServiceServer is the server API for PessoaService service.
type PessoaServiceServer interface {
	// Cria uma nova pessoa
	Criar(context.Context, *CrearPessoaRequest) (*CrearPessoaResponse, error)
}

// UnimplementedPessoaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPessoaServiceServer struct {
}

func (*UnimplementedPessoaServiceServer) Criar(ctx context.Context, req *CrearPessoaRequest) (*CrearPessoaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Criar not implemented")
}

func RegisterPessoaServiceServer(s *grpc.Server, srv PessoaServiceServer) {
	s.RegisterService(&_PessoaService_serviceDesc, srv)
}

func _PessoaService_Criar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearPessoaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PessoaServiceServer).Criar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.PessoaService/Criar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PessoaServiceServer).Criar(ctx, req.(*CrearPessoaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PessoaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.PessoaService",
	HandlerType: (*PessoaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "criar",
			Handler:    _PessoaService_Criar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pessoa-service.proto",
}
